### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by TuriGuilano** [jeffreyvankampen/jeffreyvankampen.github.io#1]
Deze code kan niet, je gebruikt een button, en plaatst in de button een a tag als attribuut met een href?

https://github.com/jeffreyvankampen/jeffreyvankampen.github.io/blob/dad798b23e5c8983c5d5d0c76148dae96a018697/detailpagina.html#L46

**Comment by jeffreyvankampen** [comment]
done
