### ISSUE TITLE
Feedback over form niet verwerkt

### ISSUE THREAD

**Issue by TuriGuilano** [jeffreyvankampen/jeffreyvankampen.github.io#2]
Je hebt je feedback over het form element niet verwerkt; die staat nu nog steeds op onvoldoende.
Verder heb je wel de site online weten te krijgen en focus / active states toegepast. 

Fix je form op correcte wijze; heb je een input? gebruik daarbij dan een label. Gebruik je uberhaupt inputs; plaats deze allen in een form.

https://github.com/jeffreyvankampen/jeffreyvankampen.github.io/blob/dad798b23e5c8983c5d5d0c76148dae96a018697/login.html#L50-L55

**Comment by jeffreyvankampen** [comment]
done
